services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.37-debian
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  backend:
    image: img
    container_name: back
    networks:
      - my-network
    ports:
      - "8080:5001"

  frontend:
    image: frontimg
    container_name: front
    networks:
      - my-network
    ports:
      - "9001:9000"

networks:
  my-network:

volumes:
  mysql_data: