name: CD to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: /back
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/schedule-sync-backend:latest
        
    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: /front
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/schedule-sync-frontend:latest

    - name: SSH to DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          cd /root/git/schedule-sync
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/schedule-sync-frontend:latest
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/schedule-sync-backend:latest
          docker compose down
          docker compose up
